# Generated by Django 5.0.2 on 2024-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='employee_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employee/'),
        ),
    ]
