# Generated by Django 5.0.2 on 2024-03-21 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('working', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Software Developer', 'Software Developer'), ('Project Manager', 'Project Manager')], max_length=20)),
                ('image', models.ImageField(upload_to='employee/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
