# Generated by Django 5.0.2 on 2024-03-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='recipe/'),
        ),
    ]
