# Generated by Django 5.0.2 on 2024-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlybudget', '0002_transactions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Personal', 'Personal'), ('Health', 'Health'), ('Transportation', 'Transportation'), ('Clothes', 'Clothes'), ('Utilities', 'Utilities'), ('Travel', 'Travel'), ('Other', 'Other'), ('Education', 'Education'), ('Entertainment', 'Entertainment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_method',
            field=models.CharField(choices=[('PayPay', 'PayPay'), ('Cash', 'Cash'), ('Credit', 'Credit'), ('E-money', 'E-money'), ('Bank', 'Bank')], max_length=50),
        ),
    ]
