# Generated by Django 5.0.2 on 2024-03-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlybudget', '0003_alter_transactions_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.IntegerField(),
        ),
    ]
