# Generated by Django 5.0.2 on 2024-03-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlybudget', '0004_alter_transactions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_method',
            field=models.CharField(choices=[('PayPay', 'PayPay'), ('Cash', 'Cash'), ('Credit', 'Credit'), ('E-money', 'E-monue'), ('Bank', 'Bank')], max_length=50),
        ),
    ]
